namespace:
  name: abfahrt

ingress:
  name: song
  hosts:
    - name: song.abfahrt.io
  secret: tls-song
  issuer: letsencrypt-issuer

service:
  name: song
  port: 80
  externalName: song.link/i/1436733646
