name: Build image

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: WyriHaximus/github-action-helm3@v3
        with:
          exec: helm lint
      - uses: WyriHaximus/github-action-helm3@v3
        with:
          exec: helm lint --strict
  template:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: WyriHaximus/github-action-helm3@v3
        with:
          exec: helm template . --debug
