name: Build and deploy

on:
  push:
    branches:
      - main
      - master

jobs:
  lint:
    name: "helm lint"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install helm chart
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm lint --strict

  deploy:
    name: "Publish to k8s"
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - name: install helm chart
        uses: WyriHaximus/github-action-helm3@v2
        with: 
          exec: helm upgrade song . --install --namespace=abfahrt --atomic
          kubeconfig: ${{ secrets.KUBECONFIG_RAW }}
