name: Build image

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: OpenAlcoholics/github-action-helm@v0.3.0
        with:
          subcommand: lint
          path: .
          namespace: abfahrt
      - uses: OpenAlcoholics/github-action-helm@v0.3.0
        with:
          subcommand: lint
          path: .
          namespace: abfahrt
          strict: true